### ISSUE TITLE
Bad dimension of the arrays in extractor.py in branch issue-auxteltarget

### ISSUE THREAD

**Issue by sylvielsstfr** [LSSTDESC/Spectractor#97]
I am trying to fight against errors in array size / matrix size in extractor.py

In calculation of regularisation matrices

There is a mismatch in size between the matrices.

  # SDC 24/05 : the next line crash
            #U.shape = (2519, 2519)
            #L.shape = (2519, 2519)
            #amplitude_priors_cov_matrix.shape = (2520, 2520)
            # ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2520 is different from 2519)
           

If I correct here, there is anyway a bad mismatch again after.

My branch is issue-auxteltarget

Should I change of branch ?

**Comment by sylvielsstfr** [comment]
cov ampl priors =  [[1020.62413073    0.            0.         ...    0.
     0.            0.        ]
 [   0.          980.02748264    0.         ...    0.
     0.            0.        ]
 [   0.            0.         1001.61854206 ...    0.
     0.            0.        ]
 ...
 [   0.            0.            0.         ... 1739.75176419
     0.            0.        ]
 [   0.            0.            0.         ...    0.
  1750.59432482    0.        ]
 [   0.            0.            0.         ...    0.
     0.         1747.37872339]]
ampl priors =  [ 21.65970555 -56.50517591 -27.8409522  ...  72.79356542  83.64298395
  79.43583027]
Nx =  2519
U.shape =  (2519, 2519)
L.shape =  (2519, 2519)
amplitude_priors.shape =  (2520,)
amplitude_priors_cov_matrix.shape =  (2520, 2520)
Q.shape =  (2519, 2519)


The current exposure under study is 

empty~ronchi170lpmm/20220316/exposure_2022031600334_postisrccd.fits
it can be found  from here /sps/lsst/groups/auxtel/data/2022

**Comment by jeremyneveu** [comment]
Problem seems to have disappeared
